export enum SidebarOptions {
    Language = "Language",
    Country = "Country",
    GameName = "Game Name", 
    Bought = "Bought",
    BankBalance = "Bank Balance",
    Rating = "Rating",
    TotalWinnings = "Total Winnings",
    Jan = "Jan",
    Feb = "Feb",
    Mar = "Mar",
    Apr = "Apr",
    May = "May",
    Jun = "Jun",
    Jul = "Jul",
    Aug = "Aug",
    Sep = "Sep",
    Oct = "Oct",
    Nov = "Nov",
    Dec = "Dec"
}